sh: mm: Fix build error
  415 |  if (WARN_ON_ONCE(params->pgprot.pgprot != PAGE_KERNEL.pgprot)
      |     ^
arch/sh/mm/init.c:424:1: error: expected expression before '}' token
  424 | }

Obviously never even compile tested.

Fixes: bfeb022f8fe4 ("mm/memory_hotplug: add pgprot_t to mhp_params")
Cc: Logan Gunthorpe <logang@deltatee.com>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>