sh: Drop -Werror from kernel Makefile
Since commit a035d552a93b ("Makefile: Globally enable fall-through
warning"), all sh builds fail with errors such as

arch/sh/kernel/disassemble.c: In function 'print_sh_insn':
arch/sh/kernel/disassemble.c:478:8: error: this statement may fall through

Since this effectively disables all build and boot tests for the
architecture, let's drop -Werror from the sh kernel Makefile until
the problems are fixed.

Cc: Gustavo A. R. Silva <gustavo@embeddedor.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Yoshinori Sato <ysato@users.sourceforge.jp>
Acked-by: Rich Felker <dalias@libc.org>