nubus: Rename pde_data var to fix conflict with external function
In file included from drivers/nubus/proc.c:24:
drivers/nubus/proc.c: In function ‘nubus_proc_rsrc_show’:
./include/linux/proc_fs.h:123:21: error: called object ‘pde_data’ is not a function or function pointer
  123 | #define PDE_DATA(i) pde_data(i)
      |                     ^~~~~~~~
drivers/nubus/proc.c:112:13: note: in expansion of macro ‘PDE_DATA’
  112 |  pde_data = PDE_DATA(inode);
      |             ^~~~~~~~
drivers/nubus/proc.c:110:30: note: declared here
  110 |  struct nubus_proc_pde_data *pde_data;
      |                              ^~~~~~~~

Fix this by renaming the local variable to "pde".  Do this everywhere
for consistency.

Reported-by: noreply@ellerman.id.au
Fixes: e7e935db128e724f ("fs: proc: store PDE()->data into inode->i_private")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>