memcg, kmem: mark cancel_charge() inline
cancel_charge() is no longer called for CONFIG_MEMCG_KMEM on NOMMU
targets, which causes a compiletime warning:

mm/memcontrol.c:2774:13: error: unused function 'cancel_charge' [-Werror,-Wunused-function]

Remove the now-incorrect #ifdef and just mark the function
'inline' like the other related helpers. This is simpler
and means we no longer have to match the #ifdef with the
caller.

Fixes: 5f3345c17079 ("memcg, kmem: further deprecate kmem.limit_in_bytes")
Reviewed-by: Muchun Song <songmuchun@bytedance.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>